# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Andamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataAndamento', models.DateField()),
                ('estado', models.CharField(choices=[('CRI', 'Criado'), ('COB', 'Cobrado'), ('BOL_GER', 'Boleto gerado'), ('PAG_INF', 'Pagamento informado'), ('PAG_CONF', 'Pagamento confirmado')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('SER', 'Serviço'), ('TAR', 'Tarifação')], max_length=20)),
                ('valorTotal', models.FloatField()),
                ('subTotalImpostos', models.FloatField()),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('INT', 'Integração'), ('FOR', 'Fornecimento')], max_length=3)),
                ('valor', models.FloatField()),
                ('dataContratacao', models.DateField()),
                ('dataRealizacao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UsoModulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('SERV', 'Serviços'), ('CONT', 'Contratos'), ('ORC', 'Orçamentos'), ('PAG', 'Pagamentos'), ('FAT', 'Faturamentos'), ('AFIL', 'Afiliação'), ('AVAL', 'Avaliação'), ('GEST_SERV', 'Gestão de serviços'), ('GEST_CONT', 'Gestão de contratos'), ('GEST_ORC', 'Gestão de orçamentos'), ('GEST_FIN', 'Gestão financeira'), ('GEST_AFIL', 'Gestão de afiliação'), ('GEST_AVAL', 'Gestão de avaliação'), ('BI_SERV', 'BI de serviço'), ('BI_CONT', 'BI de contratos'), ('BI_FIN', 'BI financeiro'), ('BI_AFIL', 'BI de afiliação'), ('BI_AVAL', 'BI de avaliação')], max_length=9)),
                ('dataHoraInicio', models.DateTimeField()),
                ('dataHoraFim', models.DateTimeField()),
                ('duracao', models.FloatField()),
                ('numTransações', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('tipo', models.CharField(choices=[('CLI', 'Cliente'), ('INT', 'Integrador'), ('FOR', 'Fornecedor')], max_length=3)),
                ('pessoa', models.CharField(choices=[('JUR', 'Pessoa jurídica'), ('FIS', 'Pessoa física')], max_length=3)),
                ('cpf', models.CharField(max_length=11)),
                ('cnpj', models.CharField(max_length=14)),
            ],
        ),
        migrations.AddField(
            model_name='servico',
            name='contratado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratado', to='GestaoFinanceira.Usuario'),
        ),
        migrations.AddField(
            model_name='servico',
            name='contratante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratante', to='GestaoFinanceira.Usuario'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='usuarioPagador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarioPagador', to='GestaoFinanceira.Usuario'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='usuarioPago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarioPago', to='GestaoFinanceira.Usuario'),
        ),
        migrations.AddField(
            model_name='andamento',
            name='pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestaoFinanceira.Pagamento'),
        ),
    ]
