# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoFinanceira', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='ano',
            field=models.IntegerField(default=2017),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagamento',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagamento',
            name='servico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='GestaoFinanceira.Servico'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='subTotalServicos',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagamento',
            name='subTotalTarifacao',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
