# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoFinanceira', '0002_auto_20170405_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='estado',
            field=models.CharField(choices=[('CRI', 'Criado'), ('COB', 'Cobrado'), ('BOL_GER', 'Boleto gerado'), ('PAG_INF', 'Pagamento informado'), ('PAG_CONF', 'Pagamento confirmado')], max_length=8),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='subTotalImpostos',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='subTotalServicos',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='subTotalTarifacao',
            field=models.FloatField(blank=True),
        ),
    ]
