# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoFinanceira', '0004_auto_20170405_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='cpf',
            new_name='CPF/CNPJ',
        ),
    ]
