# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoFinanceira', '0006_auto_20170405_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='GestaoFinanceira.Servico'),
        ),
    ]
