# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoFinanceira', '0007_auto_20170405_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='ano',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='mes',
            field=models.IntegerField(blank=True, choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='subTotalImpostos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='subTotalServicos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='subTotalTarifacao',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
