# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestaoFinanceira', '0009_auto_20170405_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='usuarioPago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarioPago', to='GestaoFinanceira.Usuario'),
        ),
    ]
